# Generated by Django 3.0.5 on 2020-04-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=3, upload_to='post_img/'),
            preserve_default=False,
        ),
    ]
