# Generated by Django 3.0.5 on 2020-04-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200418_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='FIELDNAME',
            field=models.BooleanField(default=True),
        ),
    ]
