# Generated by Django 3.0.5 on 2020-04-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_fieldname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='FIELDNAME',
            new_name='Publish',
        ),
    ]
