# Generated by Django 3.0.5 on 2020-04-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200419_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='media/post_img/default.png', upload_to='post_img/'),
        ),
    ]
