# Generated by Django 3.0.5 on 2020-04-20 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20200419_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 7, 13, 21, 154310, tzinfo=utc)),
        ),
    ]
