# Generated by Django 3.0.5 on 2020-04-20 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20200420_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 13, 14, 2, 844270)),
        ),
    ]
