# Generated by Django 3.0.5 on 2020-04-20 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_auto_20200420_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 14, 35, 18, 231157)),
        ),
    ]
