# Generated by Django 3.0.5 on 2020-04-20 12:33

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Edcaction', ckeditor.fields.RichTextField()),
                ('profile', models.ImageField(default='post_img/default.png', null=True, upload_to='post_img/')),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 4, 20, 14, 33, 11, 494378))),
                ('Publish', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
