# Generated by Django 3.0.5 on 2020-04-24 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_auto_20200420_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
